### ISSUE TITLE
Untitled Page

### ISSUE THREAD

**Issue by zakiego** [fnapi/docs#5]
![image](https://user-images.githubusercontent.com/78015359/175782829-7110b91c-4b47-492b-8a5f-a8afa2bb6d22.png)

---

When I add Title attribute, it works (Ref https://github.com/shuding/nextra/issues/235#issuecomment-966896083)

But maybe this will make twice the work, is that okay?

![Screenshot from 2022-06-26 00-41-43](https://user-images.githubusercontent.com/78015359/175782858-84ab98cf-b0be-4a6a-bc84-88ee5a4c3e05.png)

![Screenshot from 2022-06-26 00-41-53](https://user-images.githubusercontent.com/78015359/175782859-8e3fa16f-af9c-4a82-9c3a-104c67b8952f.png)

**Comment by kdy1** [comment]
I think so, twice work is acceptable at the moment.
But maybe updating nextra can be a better solution

**Comment by zakiego** [comment]
Okay. I just made the pull request (https://github.com/fnapi/docs/pull/6). Thank you!
